<?php
function lwcustom_block_info() {
  $blocks = [];
  $blocks['lw_translations_toc'] = [
    'info' => t('LW translations TOC'),
  ];

  return $blocks;
}

function lwcustom_block_view($delta='') {
  $block = [];

  $books = [
    285,
    371,
    382,
  ];

  switch ($delta) {
    case 'lw_translations_toc':
      $block['content'] = [];

      foreach ($books as $book_id) {
        $book_node = node_load($book_id);

        $description = [
          '#type' => 'markup',
          '#markup' => check_markup($book_node->body['und'][0]['value'], 'wikitypetext'),
        ];

        $tree = menu_tree_output(menu_tree_all_data(book_menu_name($book_id)));
        reset($tree);
        $tree_id = key($tree);
        $inner_tree = $tree[$tree_id];

        $below = $inner_tree['#below'];
        reset($below);
        $first_key = key($below);
        $prepend_key = $first_key - 1;
        $below[$prepend_key] = $description;

        $block['content'][] = $tree;
      }

      break;
  }

  return $block;
}
