<?php
function lwcustom_block_info() {
  $blocks = [];
  $blocks['lw_translations_toc'] = [
    'info' => t('LW translations TOC'),
  ];

  return $blocks;
}

function lwcustom_block_view($delta='') {
  $block = [];

  $books = [
    285,
    371,
    382,
  ];

  switch ($delta) {
    case 'lw_translations_toc':
      $block['content'] = [];

      foreach ($books as $book_id) {
        $book_node = node_load($book_id);
        $block['content'][] = [
          [
            '#type' => 'markup',
            '#markup' => check_markup('# ' . $book_node->title, 'wikitypetext'),
          ],
          [
            '#type' => 'markup',
            '#markup' => check_markup($book_node->body['und'][0]['value'], 'wikitypetext'),
          ],
        ];
        $block['content'][] = menu_tree_output(
          menu_tree_all_data(book_menu_name($book_id))
        );
      }

      break;
  }

  return $block;
}
